/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
  RouterHistory,
} from '@stencil/router';


export namespace Components {

  interface AppAjout {}
  interface AppAjoutAttributes extends StencilHTMLAttributes {}

  interface AppDetail {
    'match': MatchResults;
  }
  interface AppDetailAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppEdition {
    'match': MatchResults;
  }
  interface AppEditionAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppProfile {
    'match': MatchResults;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface AppSuppression {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface AppSuppressionAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppAjout': Components.AppAjout;
    'AppDetail': Components.AppDetail;
    'AppEdition': Components.AppEdition;
    'AppHome': Components.AppHome;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
    'AppSuppression': Components.AppSuppression;
  }

  interface StencilIntrinsicElements {
    'app-ajout': Components.AppAjoutAttributes;
    'app-detail': Components.AppDetailAttributes;
    'app-edition': Components.AppEditionAttributes;
    'app-home': Components.AppHomeAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
    'app-suppression': Components.AppSuppressionAttributes;
  }


  interface HTMLAppAjoutElement extends Components.AppAjout, HTMLStencilElement {}
  var HTMLAppAjoutElement: {
    prototype: HTMLAppAjoutElement;
    new (): HTMLAppAjoutElement;
  };

  interface HTMLAppDetailElement extends Components.AppDetail, HTMLStencilElement {}
  var HTMLAppDetailElement: {
    prototype: HTMLAppDetailElement;
    new (): HTMLAppDetailElement;
  };

  interface HTMLAppEditionElement extends Components.AppEdition, HTMLStencilElement {}
  var HTMLAppEditionElement: {
    prototype: HTMLAppEditionElement;
    new (): HTMLAppEditionElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppSuppressionElement extends Components.AppSuppression, HTMLStencilElement {}
  var HTMLAppSuppressionElement: {
    prototype: HTMLAppSuppressionElement;
    new (): HTMLAppSuppressionElement;
  };

  interface HTMLElementTagNameMap {
    'app-ajout': HTMLAppAjoutElement
    'app-detail': HTMLAppDetailElement
    'app-edition': HTMLAppEditionElement
    'app-home': HTMLAppHomeElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
    'app-suppression': HTMLAppSuppressionElement
  }

  interface ElementTagNameMap {
    'app-ajout': HTMLAppAjoutElement;
    'app-detail': HTMLAppDetailElement;
    'app-edition': HTMLAppEditionElement;
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'app-suppression': HTMLAppSuppressionElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
